tablelandnetwork/tableland-js

packages/local/package.json, packages/sdk/package.json, packages/sdk/src/helpers/config.ts, packages/sdk/src/helpers/index.ts, packages/sdk/src/registry/utils.ts, packages/sdk/src/validator/client/index.ts, packages/sdk/src/validator/index.ts, packages/sdk/src/validator/query.ts, packages/sdk/test/browser/server/package-lock.json, packages/sdk/test/database.test.ts, packages/sdk/test/validator.test.ts, packages/sdk/test/validator/config.json
This enables specifying an api key that bypasses the Validator's rate limiting.
You can pass an `apiKey` parameter to the `Validator` and `Database` classes, which is converted to the correct header and send with read requests.
Example use:
```
new Validator({ apiKey, ... });
new Database({ apiKey, ... });
```
=> Enable specifying api key in config

packages/local/package.json, packages/local/src/main.ts, packages/local/src/util.ts, packages/local/src/validators.ts, packages/local/test/e2e.test.ts, packages/local/test/start.test.ts, packages/sdk/package.json, packages/sdk/src/helpers/config.ts
As an improvement working toward fixing https://github.com/tablelandnetwork/local-tableland/issues/379 this PR introduces behavior that check if the registry has been deployed before starting the Validator.   If the contract is **not** deployed an error is thrown.  This will make CI tests fail immediately and obviously, which will make the reason for failure more obvious.
Along with requiring the existence of the registry on chain for successful startup, there are a few other changes:
- This reverts some of the port failure retry logic since that didn't solve the issue with CI failures.
- This moves the startup and shutdown tests into their own test file
- This moves the hard coded registry contract address up one level, from the validator.ts file to the main.ts file. I needed to do this …
=> throw an error if the registry contract hasn't been deployed

package-lock.json, packages/sdk/src/validator/index.ts, packages/sdk/src/validator/tables.ts
Can't use the `Schema` type without this.
I was trying to use `type Schema = Table["schema"]` and then exporting things that use `Schema`, but of course got a ts error that the SDK's internal `Schema` type can't be named, which makes sense since it wasn't exported.
Figure we might as well export `Column` as well.
=> Export Schema and Column types so they can be used externally

package-lock.json, packages/local/package.json, packages/local/src/main.ts
Hardhat has an RPC API that contains methods to take a snapshot of the chain state, and then revert to a given state.
Docs are here: https://hardhat.org/hardhat-network/docs/reference#evm_snapshot
This is useful for testing contracts, but the local tableland network becomes out of sync when this happens because the tables materialized by the Validator are no longer valid.
This PR enables local tableland users who want to snapshot and revert to do so in a way that keeps the Validator up to date with the reverted chain state.
The mechanism used here to re-sync the validator with the chain is to simple shutdown and restart the validator.  The methods needed to accomplish that haven't been public, so this PR simply does a small refactor and exposes a new method called `restartValidator`.
=> Expose a Local Tableland method that restarts the validator

packages/sdk/src/helpers/config.ts, packages/sdk/test/aliases.test.ts
This current aliases config helper will overwrite any existing aliases file when you create a new table.  This was an oversight during initial development.  This PR changes the behaviour to add to the file as new tables are created.
=> (sdk) Add alias to file instead of overwriting

package-lock.json, packages/cli/package.json, packages/cli/src/utils.ts, packages/local/package.json, packages/sdk/package.json, packages/sdk/src/helpers/chains.ts, packages/sdk/test/chains.test.ts
If you try to create a table on OP Goerli, it actually uses the `optimism-goerli-staging` network instead of `optimism-goerli`. This filters out the "staging" network and adds tests accordingly. Also, I squeezed in a dep bump for `@tableland/sdk`. Closes #58.
There's a simple one liner added to `helpers/chains.ts`:
```ts
const filtered = mapped.filter(
([chainName]) => chainName !== "optimism-goerli-staging"
);
```
This is then used in the `supportedChains` object, which gets exported and is used in clients like the CLI. Note that the CLI had to implement similar logic to what's described above. The change in the SDK will allow us to remove that check in the CLI, but it's not required at the moment; everything should still work as expected in the CLI.
Wrt to the …
=> fix: filter out `optimism-goerli-staging` from chains

package-lock.json, packages/sdk/API.md, packages/sdk/package.json, packages/sdk/src/database.ts, packages/sdk/src/helpers/await.ts, packages/sdk/src/helpers/chains.ts, packages/sdk/src/helpers/config.ts, packages/sdk/src/helpers/index.ts, packages/sdk/src/lowlevel.ts, packages/sdk/src/registry/utils.ts, packages/sdk/src/statement.ts, packages/sdk/src/validator/health.ts, packages/sdk/src/validator/index.ts, packages/sdk/src/validator/query.ts, packages/sdk/src/validator/receipt.ts, packages/sdk/src/validator/tables.ts, packages/sdk/src/validator/version.ts, packages/sdk/test/await.test.ts, packages/sdk/test/chains.test.ts, packages/sdk/test/database.test.ts, packages/sdk/test/lowlevel.test.ts, packages/sdk/test/statement.test.ts, packages/sdk/test/thirdparty.test.ts
The initial work for this PR is located in https://github.com/tablelandnetwork/js-tableland/pull/576/files
_Summary
Fixes abort controller handling which allows a user to abort and configure the polling timeout and interval for SDK methods that poll the gateway for a receipt._
_Details
The core of this PR was adding the wiring to make the underlying polling handling aware of the user's abort controller. However, I found the API to be unintuitive and spent some time refactoring how a user goes about providing a abort-able controller with a custom timeout and polling interval. See comments below for details._
_NOTE: This would be a breaking API change and therefore would require a major version bump. We probably could make the core fix while not breaking the API, but I don't think there's …
=> fix abort controller handling

package-lock.json, packages/local/test/e2e.test.ts, packages/sdk/package.json, packages/sdk/src/database.ts, packages/sdk/src/helpers/await.ts, packages/sdk/src/registry/index.ts, packages/sdk/src/registry/utils.ts, packages/sdk/src/statement.ts, packages/sdk/test/chains.test.ts, packages/sdk/test/database.test.ts, packages/sdk/test/statement.test.ts, packages/sdk/test/thirdparty.test.ts
The D1 API changed, so our API is no longer compatible. This introduces some breaking changes since some of the statement & database methods' parameters, generic types, and returned types have to be altered for conformance purposes.
For reference, [these are the old](https://github.com/cloudflare/workerd/commit/72d6915e19fb56de8373144bf922afa253b378cc) APIs, and [these are the new ones](https://github.com/cloudflare/workerd/blob/main/types/defines/d1.d.ts). The interfaces the statement methods must conform to are the following—notice the generic type `T = unknown` is now `T = Record<string, unknown>` in most of these:
```ts
// old
bind(...values: any[]): D1PreparedStatement;
first<T = unknown>(colName?: string): Promise<T>;
run<T = unknown>(): Promise<D1Result<T>>;
all<T = unknown>(): …
```
=> refactor: D1 API conformance

package-lock.json, packages/cli/package.json, packages/local/package.json
Updates the version for `cli` to `5.3.1` and `local` to `2.1.1`—both patch bumps.
Both packages had dep updates for the `@tableland/sdk@^5.0.0`. The CLI has a new `@tableland/node-helpers` dep along with some refactoring/bug fixes that don't impact the user.
N/A
=> chore: bump `cli`, `local` with patch version

package-lock.json, packages/cli/package.json, packages/node-helpers/package.json, packages/node-helpers/src/index.ts
The `node-helpers` package was exporting things from `"./utils"`, but this should have been `"./utils.js"`. This impacted the CLI since it uses the helpers, so no commands would work. Also includes some dependabot dep bumps; closes #56, #71, #72. 
Prior to the fix, you would run into this error when trying to actually use `jsonFileAliases` from `node-helpers` as well as any CLI commands:
```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/dtb/tbl/tableland-js/packages/node-helpers/dist/esm/utils' imported from /Users/dtb/tbl/tableland-js/packages/node-helpers/dist/esm/index.js
```
The changes bump the `cli` to 5.3.2 and `node-helpers` to 0.0.2.
- Built the CLI and tested the `dist/cli.js` commands locally.
- Symlink in a test Node.js project to import/use `jsonFileAliase` from …
=> fix(node-helpers|cli): `node-helpers` missing export

.github/workflows/test.yml, package-lock.json, package.json, packages/cli/package.json, packages/cli/src/commands/read.ts, packages/local/package.json, packages/local/registry/package-lock.json, packages/local/registry/package.json, packages/sdk/package.json, packages/sdk/test/validator.test.ts
This upgrades the `@tableland/local` `hardhat` dependency version, and switches our invalid JSON error message detection to something that works for all LTS versions of node.js
add node version 20 to the matrix
Tests were updated to more lenient error message matching
`local`'s current version of Hardhat does not work with Node.js version 20.x.x  
If you try to use it you will receive the following error
```
unrecoverable error
Error: WARNING: You are using a version of Node.js that is not supported, and it may work incorrectly, or not work at all. See https://hardhat.org/nodejs-versions
```
Note, the newest version of `hardhat` works with all node.js LTS versions
Only a small change needed here.  The read command is using string matching to detect invalid json as a result of incorrect …
=> Enable usage with Node.js 20 LTS version

package-lock.json, packages/cli/package.json, packages/local/package.json, packages/node-helpers/package.json, packages/sdk/package.json, packages/sdk/src/helpers/ethers.ts, packages/sdk/src/registry/controller.ts, packages/sdk/src/registry/create.ts, packages/sdk/src/registry/run.ts, packages/sdk/src/registry/transfer.ts
This fixes an issue where Mumbai txs were always failing for both creates and writes. It bumps the gas limit up by 20% for all Polygon chains. The CLI package has been updated with a patch bump to incorporate the new SDK version's patch. Also, small package.json updates were made for GH repo links in all packages. Closes #98.
It affects all state altering methods. This includes `create` and `mutate` methods for both single and batch statements, setting/locking controllers, and transfers.
You can see a test create and write tx here, where the gas limit leaves about 20% of extra room:
- create: [0xd36a73256b38b866ebda65dff619174145768f35a2cb179f2ebc0f3832344bbc](https://mumbai.polygonscan.com/tx/0xd36a73256b38b866ebda65dff619174145768f35a2cb179f2ebc0f3832344bbc)
- mutate: …
=> fix: mumbai failing to due gas limit issues

packages/sdk/package.json, packages/sdk/src/database.ts, packages/sdk/src/registry/index.ts, packages/sdk/test/database.test.ts, packages/sdk/test/registry.test.ts
Drop deprecated `Database.readOnly` and `Registry.runSQL` methods. Closes #105, #106.
See above.
Removed tests that were previously using this logic.
=> feat: drop deprecated sdk methods

package-lock.json
#108 was merged without running `npm install` hence the package-lock.json file has the wrong sdk version.  This updates package lock.
=> (sdk) update `package-lock.json` with sdk version

package-lock.json, packages/sdk/package.json, packages/sdk/src/helpers/index.ts
In order to make the ethers.js `contract.estimateGas` method more easily available to SDK consumers, we need to export our internal `getContractAndOverrides` method.
This change is needed for the feature in https://github.com/tablelandnetwork/studio/pull/173
=> (sdk) export helper to get registry contract

package-lock.json
`npm install` wasn't run before #129 was merged, so package-lock.json needed one change before publishing.
=> update package lock before publish

package-lock.json, packages/cli/package.json, packages/cli/src/commands/index.ts, packages/cli/src/commands/studio.ts, packages/sdk/src/validator/client/validator.ts
In order to combine our CLIs we decided to add the studio cli commands as a sub command.  This is accomplished by simply importing the studio cli code and loading the commands under `studio` 
Related to: https://github.com/tablelandnetwork/studio/pull/241
fixes: https://linear.app/tableland/issue/ENG-713/move-all-existing-studio-cli-commands-to-a-sub-command-in-the-original
=> (cli) add studio commands

package-lock.json, packages/local/package.json, packages/local/test/fork.test.ts
The `local` package should get it's `sdk` dependency updated, but the chain forking tests keep timing out in the dependabot PR.  This PR manually bumps the sdk and skips the fork tests.  
My thinking here is that we can always run the fork tests locally during development and review if a change potentially affects that feature. Running them locally takes 15-20 minutes, but for CI it's nice if it takes an hour or more which is too much.
=> (local) bump sdk dep and skip fork tests

package-lock.json, packages/local/src/validators.ts, packages/node-helpers/test/setup.ts
I've been noticing that `local` extends the validator config and does so without including a new line character at the end of the file.  This means that if you accidentally commit while the validator is running you potentially commit a violation of this repo's prettier.
This PR includes the EOL character in the generated config file.
=> (local) fix deviation from prettier rule in config

packages/local/src/util.ts
With recent upgrades the messages hardhat logs have changed a little bit.  This PR filters out a few new log messages that come in at a regular basis regardless of if there is anything happening on the network.
This also alphabetizes the log message filters.
=> (local) add more extraneous log filters

package-lock.json, packages/local/package.json, packages/local/src/main.ts
I've been getting an error recently where the SIGINT event is being received twice by local tableland.
After some debugging, it looks like when Ctrl+C is pressed, the shell sends a SIGINT signal to the foreground process/process-group. If the foreground process is Node, it's only sent to the Node process. But when it's an npm process with a child Node process attached, the SIGINT is sent to both npm and Node processes.
The Node process receives the signal a second time is because the npm process listens to signals and relays them to the child Node process.
This change ensures that an instance of LT will not try to shutdown twice in parallel if the signal is received twice.
=> (local) ensure shutdown cannot be run repeatedly

package-lock.json, packages/cli/package.json, packages/cli/src/utils.ts, packages/sdk/package.json, packages/sdk/src/helpers/chains.ts, packages/sdk/src/helpers/ethers.ts, packages/sdk/src/validator/client/validator.ts, packages/sdk/test/chains.test.ts
Adds Base Sepolia chain support.
N/A
- Updated existing tests to include Base.
- Created a table with the React JS template: [here](https://testnets.tableland.network/api/v1/tables/84532/2)
=> feat(sdk|cli): add Base Sepolia
